name: docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow
        run:  git fetch --prune --unshallow
      - name: Lint Dockerfile
        run:  docker run --rm -i hadolint/hadolint < Dockerfile
      - name: Build Docker Container
        run:  docker build -t gloc .
      - name: Test Container
        run:  docker run -v ${PWD}:/workdir gloc .
